---
driver:
  name: vagrant
  product_version: 14.1.1

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[kibana_wrapper_cookbook::default]
    verifier:
      inspec_tests:
        - test/unit/spec
